#!/usr/bin/env bash

#A script that accepts 4 params and copies a file to my server
# scp must transfer the file to the user home directory ~/
#Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2: ~/"
fi
