#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on

#update system and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

#allow request through port 80
sudo ufw allow "Nginx HTTP"

#Hello World index page
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

#configure nginx with requirements listed above
_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;

    location / {
            try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location /404.html {
        internal;
    }

    if (\$request_filename ~ redirect_me){
        rewrite ^ https:/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}
"

#404 error redirection
echo "Ceci n'est pas une page" > /var/www/html/404.html


echo "$_config" > /etc/nginx/sites-available/default

sudo service nginx restart
