#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.


# Check if the password argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <mysql_root_password>"
  exit 1
fi

PASSWORD=$1

# Get the current date in day-month-year format
DATE=$(date +%d-%m-%Y)

mysqldump -u root -p"$PASS" --all-databases > backup.sql

# Define the backup file name
ARCHIVE_FILE="$DATE.tar.gz"

tar -czvf "$ARCHIVE_FILE" backup.sql
