#!/usr/bin/env bash
#Prints message correspoding to number
counter=1
while [ "$counter" -le 20 ]
do
    echo "$counter"
    if [ "$counter" = 4 ]
    then
        echo "bad luck from China"
    elif [ "$counter" = 9 ]
    then
        echo "bad luck from Japan"
    elif [ "$counter" = 17 ]
    then
        echo "bad luck from Italy"
    fi
    ((counter++))
done
