#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes
seconds=1
hour=0
while [ "$hour" -le 12 ]
do
    echo "Hour:$hour"
    while [ "$seconds" -le 59 ]
    do
        echo "$seconds"
        ((seconds++))
    done
    ((hour++))
    seconds=1
done
